/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:47cdb747-d059-4eba-887e-0da4b6273d37",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_PbB4Q7zD2",
    "aws_user_pools_web_client_id": "5on0a0c1hr7ugg0pscfsk6tj6g",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://te62vbjourhcfjnhoagyiot4xq.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ngzd42c6zzaw5cirlpkwx66u6y",
    "aws_user_files_s3_bucket": "note-image64403-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
